// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbLaZKWxTdxC7wgAwNV8-8hpG1fPy32o',
    appId: '1:516374573363:web:408c6a308d79d31a484e46',
    messagingSenderId: '516374573363',
    projectId: 'iot-project-welfarezone-month1',
    authDomain: 'iot-project-welfarezone-month1.firebaseapp.com',
    databaseURL:
        'https://iot-project-welfarezone-month1-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-welfarezone-month1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2mnskgb8ttqPQuOG86Vn7iDNEi9VYkLc',
    appId: '1:516374573363:android:ad9409dd1bf4f7e3484e46',
    messagingSenderId: '516374573363',
    projectId: 'iot-project-welfarezone-month1',
    databaseURL:
        'https://iot-project-welfarezone-month1-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-welfarezone-month1.appspot.com',
  );
}
